#!/bin/bash

curl https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png > google_logo.png

aws s3 cp google_logo.png s3://ds2022-hta4yb/

aws s3 presign s3://ds2022-hta4yb/google_logo.png --expires-in 604800
